### ISSUE TITLE
Peer to Peer Code Review

### ISSUE THREAD

**Issue by itsmraga-hub** [kendoriddy/portfolio-website#12]
# ⚠️ Issue #2 

- Great job so far 🚀. I would however recommend you to use CSS to add either a border-top or a border-bottom to your project for better HTML practices. This way, the border will have no effect on the actual layout of the project on the browser.
- It is considered among the best practices, especially for accessibility purposes to add descriptive alt text to all images in a project.

**Comment by kendoriddy** [comment]
Thank you. All suggestions noted and corrections made.
